services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress
    container_name: wordpress_cms
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress_data:/var/www/html

  nextjs:
    build: .
    container_name: nextjs_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - wordpress
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    develop:
      watch:
        - action: sync
          path: .
          target: .
          ignore:
            - node_modules/
        - action: restart
          path: package.json

volumes:
  db_data:
  wordpress_data:
